---
deployment:
  tasks:
    - export DEPLOY_SERVER_PATH=/home/amirmuha/portfolio/server/
    - export DEPLOY_CLIENT_PATH=/home/amirmuha/portfolio/client/
    - cp ./server $DEPLOY_SERVER_PATH
    - cd $DEPLOY_CLIENT_PATH
    - npm install
    - gatsby build
    - gatsby server
