---
deployment:
  tasks:
    - export DEPLOYPATH_CLIENT=/home/amirmuha/portfolio.amirmuha.com/
    - export DEPLOYPATH_SERVER=/home/amirmuha/portfolio.server.amirmuha.com/
    - /bin/cp -R client/public/* $DEPLOYPATH_CLIENT
    - /bin/cp -Rp server/{dist/*,package.json,package-lock.json,schema.gql} $DEPLOYPATH_SERVER
