"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
exports.__esModule = true;
exports.DeleteQuestionMutation = exports.DeleteTechMutation = exports.DeleteTechCategoryMutation = exports.DeleteSketchMutation = exports.DeleteProjectMutation = exports.DeleteStackMutation = exports.UpdateQuestionMutation = exports.UpdateTechCategoryMutation = exports.UpdateSummarySketchMutation = exports.UpdateDownloadLinkSketchMutation = exports.UpdateImageSketchMutation = exports.UpdateDescriptionSketchMutation = exports.UpdateProjectNameMutation = exports.UpdateProjectgithub_urlMutation = exports.UpdateProjectAppUrlMutation = exports.UpdateImageMutation = exports.UpdateProjectTypeMutation = exports.UpdateProjectSummaryMutation = exports.CreateQuestionMutation = exports.CreateTechMutation = exports.CreateTechCategoryMutation = exports.CreateSketchMutation = exports.CreateProjectMutation = exports.CreateStackMutation = exports.UploadMultipleFileMutation = exports.UploadSingleFileMutation = exports.SubmitAdminMutation = exports.LogoutMutation = exports.LoginMutation = exports.ConfirmEmailMutation = void 0;
var client_1 = require("@apollo/client");
exports.ConfirmEmailMutation = (0, client_1.gql)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  mutation ConfirmEmail($code: Int!, $email: String!) {\n    confirmEmail(code: $code, email: $email)\n  }\n"], ["\n  mutation ConfirmEmail($code: Int!, $email: String!) {\n    confirmEmail(code: $code, email: $email)\n  }\n"
    // ##################################
    // ############### Create Mutations
    // ##################################
])));
// ##################################
// ############### Create Mutations
// ##################################
exports.LoginMutation = (0, client_1.gql)(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  mutation Login($email: String!, $password: String!) {\n    login(data: { email: $email, password: $password }) {\n      token\n    }\n  }\n"], ["\n  mutation Login($email: String!, $password: String!) {\n    login(data: { email: $email, password: $password }) {\n      token\n    }\n  }\n"])));
exports.LogoutMutation = (0, client_1.gql)(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  mutation Logout {\n    logout\n  }\n"], ["\n  mutation Logout {\n    logout\n  }\n"])));
exports.SubmitAdminMutation = (0, client_1.gql)(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  mutation SubmitAdmin(\n    $email: String!\n    $password: String!\n    $fname: String!\n    $lname: String!\n    $linkedIn: String!\n    $whatsapp: String!\n    $instagram: String!\n    $github: String!\n    $heroImage: String!\n    $resumes: [String!]!\n  ) {\n    createAdmin(\n      data: {\n        email: $email\n        password: $password\n        fname: $fname\n        lname: $lname\n        linkedIn: $linkedIn\n        whatsapp: $whatsapp\n        instagram: $instagram\n        github: $github\n        heroImage: $heroImage\n        resumes: { set: $resumes }\n      }\n    ) {\n      id\n      email\n      fname\n      lname\n      resumes\n    }\n  }\n"], ["\n  mutation SubmitAdmin(\n    $email: String!\n    $password: String!\n    $fname: String!\n    $lname: String!\n    $linkedIn: String!\n    $whatsapp: String!\n    $instagram: String!\n    $github: String!\n    $heroImage: String!\n    $resumes: [String!]!\n  ) {\n    createAdmin(\n      data: {\n        email: $email\n        password: $password\n        fname: $fname\n        lname: $lname\n        linkedIn: $linkedIn\n        whatsapp: $whatsapp\n        instagram: $instagram\n        github: $github\n        heroImage: $heroImage\n        resumes: { set: $resumes }\n      }\n    ) {\n      id\n      email\n      fname\n      lname\n      resumes\n    }\n  }\n"])));
exports.UploadSingleFileMutation = (0, client_1.gql)(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  mutation UploadFile($file: Upload!) {\n    uploadSingleFile(file: $file)\n  }\n"], ["\n  mutation UploadFile($file: Upload!) {\n    uploadSingleFile(file: $file)\n  }\n"])));
exports.UploadMultipleFileMutation = (0, client_1.gql)(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  mutation UploadFiles($files: [Upload!]!) {\n    uploadMultipleFiles(files: $files)\n  }\n"], ["\n  mutation UploadFiles($files: [Upload!]!) {\n    uploadMultipleFiles(files: $files)\n  }\n"])));
exports.CreateStackMutation = (0, client_1.gql)(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n  mutation CreateStack($id: String!, $image: String!) {\n    updateAdmin(data: { stack: { push: $image } }, where: { id: $id })\n  }\n"], ["\n  mutation CreateStack($id: String!, $image: String!) {\n    updateAdmin(data: { stack: { push: $image } }, where: { id: $id })\n  }\n"])));
exports.CreateProjectMutation = (0, client_1.gql)(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n  mutation CreateProject(\n    $for: String\n    $name: String!\n    $image: String!\n    $type: String!\n    $github_url: String!\n    $app_url: String!\n    $summary: String!\n  ) {\n    createProject(\n      data: {\n        name: $name\n        image: $image\n        type: $type\n        github_url: $github_url\n        app_url: $app_url\n        summary: $summary\n        admin: { connect: { email: $for } }\n      }\n    ) {\n      id\n      name\n      image\n      type\n      github_url\n      app_url\n      summary\n    }\n  }\n"], ["\n  mutation CreateProject(\n    $for: String\n    $name: String!\n    $image: String!\n    $type: String!\n    $github_url: String!\n    $app_url: String!\n    $summary: String!\n  ) {\n    createProject(\n      data: {\n        name: $name\n        image: $image\n        type: $type\n        github_url: $github_url\n        app_url: $app_url\n        summary: $summary\n        admin: { connect: { email: $for } }\n      }\n    ) {\n      id\n      name\n      image\n      type\n      github_url\n      app_url\n      summary\n    }\n  }\n"
    // export const CreateMessageMutation = gql``
])));
// export const CreateMessageMutation = gql``
exports.CreateSketchMutation = (0, client_1.gql)(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n  mutation CreateSketch(\n    $projectId: String!\n    $summary: String!\n    $description: String!\n    $download_link: String!\n    $image: String!\n    $title: String!\n  ) {\n    createSketch(\n      data: {\n        title: $title\n        description: $description\n        summary: $summary\n        download_link: $download_link\n        image: $image\n        project: { connect: { id: $projectId } }\n      }\n    ) {\n      id\n      title\n      summary\n      description\n      download_link\n      image\n      project_id\n    }\n  }\n"], ["\n  mutation CreateSketch(\n    $projectId: String!\n    $summary: String!\n    $description: String!\n    $download_link: String!\n    $image: String!\n    $title: String!\n  ) {\n    createSketch(\n      data: {\n        title: $title\n        description: $description\n        summary: $summary\n        download_link: $download_link\n        image: $image\n        project: { connect: { id: $projectId } }\n      }\n    ) {\n      id\n      title\n      summary\n      description\n      download_link\n      image\n      project_id\n    }\n  }\n"])));
exports.CreateTechCategoryMutation = (0, client_1.gql)(templateObject_10 || (templateObject_10 = __makeTemplateObject(["\n  mutation CreateTechCategory($name: String!, $projectId: String!) {\n    createTechCategory(\n      data: { name: $name, project: { connect: { id: $projectId } } }\n    ) {\n      id\n      name\n    }\n  }\n"], ["\n  mutation CreateTechCategory($name: String!, $projectId: String!) {\n    createTechCategory(\n      data: { name: $name, project: { connect: { id: $projectId } } }\n    ) {\n      id\n      name\n    }\n  }\n"])));
exports.CreateTechMutation = (0, client_1.gql)(templateObject_11 || (templateObject_11 = __makeTemplateObject(["\n  mutation CreateTech($name: String!, $techCategoryId: String!) {\n    createTech(\n      data: {\n        name: $name\n        tech_categories: { connect: { id: $techCategoryId } }\n      }\n    ) {\n      id\n      name\n    }\n  }\n"], ["\n  mutation CreateTech($name: String!, $techCategoryId: String!) {\n    createTech(\n      data: {\n        name: $name\n        tech_categories: { connect: { id: $techCategoryId } }\n      }\n    ) {\n      id\n      name\n    }\n  }\n"
    // export const CreateAboutMutation = gql``
])));
// export const CreateAboutMutation = gql``
exports.CreateQuestionMutation = (0, client_1.gql)(templateObject_12 || (templateObject_12 = __makeTemplateObject(["\n  mutation CreateQuestion(\n    $question: String!\n    $answer: String!\n    $projectId: String!\n  ) {\n    createQuestion(\n      data: {\n        question: $question\n        project: { connect: { id: $projectId } }\n        answer: { create: { answer: $answer } }\n      }\n    ) {\n      id\n      question\n      answer {\n        id\n        answer\n      }\n    }\n  }\n"], ["\n  mutation CreateQuestion(\n    $question: String!\n    $answer: String!\n    $projectId: String!\n  ) {\n    createQuestion(\n      data: {\n        question: $question\n        project: { connect: { id: $projectId } }\n        answer: { create: { answer: $answer } }\n      }\n    ) {\n      id\n      question\n      answer {\n        id\n        answer\n      }\n    }\n  }\n"
    // // ##################################
    // // ############### Update Mutations
    // // ##################################
])));
// // ##################################
// // ############### Update Mutations
// // ##################################
exports.UpdateProjectSummaryMutation = (0, client_1.gql)(templateObject_13 || (templateObject_13 = __makeTemplateObject(["\n  mutation UpdateProjectSummary($id: String!, $summary: String) {\n    updateProject(data: { summary: { set: $summary } }, where: { id: $id }) {\n      summary\n    }\n  }\n"], ["\n  mutation UpdateProjectSummary($id: String!, $summary: String) {\n    updateProject(data: { summary: { set: $summary } }, where: { id: $id }) {\n      summary\n    }\n  }\n"])));
exports.UpdateProjectTypeMutation = (0, client_1.gql)(templateObject_14 || (templateObject_14 = __makeTemplateObject(["\n  mutation UpdateProjectType($id: String!, $type: String) {\n    updateProject(data: { type: { set: $type } }, where: { id: $id }) {\n      type\n    }\n  }\n"], ["\n  mutation UpdateProjectType($id: String!, $type: String) {\n    updateProject(data: { type: { set: $type } }, where: { id: $id }) {\n      type\n    }\n  }\n"])));
exports.UpdateImageMutation = (0, client_1.gql)(templateObject_15 || (templateObject_15 = __makeTemplateObject(["\n  mutation UpdateImage(\n    $file: Upload!\n    $id: String!\n    $prevname: String!\n    $field: String\n  ) {\n    updateImage(file: $file, id: $id, prevname: $prevname, field: $field)\n  }\n"], ["\n  mutation UpdateImage(\n    $file: Upload!\n    $id: String!\n    $prevname: String!\n    $field: String\n  ) {\n    updateImage(file: $file, id: $id, prevname: $prevname, field: $field)\n  }\n"])));
exports.UpdateProjectAppUrlMutation = (0, client_1.gql)(templateObject_16 || (templateObject_16 = __makeTemplateObject(["\n  mutation UpdateProjectAppUrl($id: String!, $app_url: String) {\n    updateProject(data: { app_url: { set: $app_url } }, where: { id: $id }) {\n      app_url\n    }\n  }\n"], ["\n  mutation UpdateProjectAppUrl($id: String!, $app_url: String) {\n    updateProject(data: { app_url: { set: $app_url } }, where: { id: $id }) {\n      app_url\n    }\n  }\n"])));
exports.UpdateProjectgithub_urlMutation = (0, client_1.gql)(templateObject_17 || (templateObject_17 = __makeTemplateObject(["\n  mutation UpdateProjectGitHubUrl($id: String!, $github_url: String) {\n    updateProject(\n      data: { github_url: { set: $github_url } }\n      where: { id: $id }\n    ) {\n      github_url\n    }\n  }\n"], ["\n  mutation UpdateProjectGitHubUrl($id: String!, $github_url: String) {\n    updateProject(\n      data: { github_url: { set: $github_url } }\n      where: { id: $id }\n    ) {\n      github_url\n    }\n  }\n"])));
exports.UpdateProjectNameMutation = (0, client_1.gql)(templateObject_18 || (templateObject_18 = __makeTemplateObject(["\n  mutation UpdateProjectName($id: String!, $name: String) {\n    updateProject(data: { name: { set: $name } }, where: { id: $id }) {\n      name\n    }\n  }\n"], ["\n  mutation UpdateProjectName($id: String!, $name: String) {\n    updateProject(data: { name: { set: $name } }, where: { id: $id }) {\n      name\n    }\n  }\n"
    // export const UpdateMessageMutation = gql``
])));
// export const UpdateMessageMutation = gql``
exports.UpdateDescriptionSketchMutation = (0, client_1.gql)(templateObject_19 || (templateObject_19 = __makeTemplateObject(["\n  mutation UpdateSketchDescription($id: String!, $description: String!) {\n    updateSketch(\n      data: { description: { set: $description } }\n      where: { id: $id }\n    ) {\n      id\n      title\n      description\n      summary\n      image\n      download_link\n    }\n  }\n"], ["\n  mutation UpdateSketchDescription($id: String!, $description: String!) {\n    updateSketch(\n      data: { description: { set: $description } }\n      where: { id: $id }\n    ) {\n      id\n      title\n      description\n      summary\n      image\n      download_link\n    }\n  }\n"])));
exports.UpdateImageSketchMutation = (0, client_1.gql)(templateObject_20 || (templateObject_20 = __makeTemplateObject(["\n  mutation UpdateSketchImage($id: String!, $image: String!) {\n    updateSketch(data: { image: { set: $image } }, where: { id: $id }) {\n      id\n      title\n      description\n      summary\n      image\n      download_link\n    }\n  }\n"], ["\n  mutation UpdateSketchImage($id: String!, $image: String!) {\n    updateSketch(data: { image: { set: $image } }, where: { id: $id }) {\n      id\n      title\n      description\n      summary\n      image\n      download_link\n    }\n  }\n"])));
exports.UpdateDownloadLinkSketchMutation = (0, client_1.gql)(templateObject_21 || (templateObject_21 = __makeTemplateObject(["\n  mutation UpdateSketchDownloadLink($id: String!, $download_link: String!) {\n    updateSketch(\n      data: { download_link: { set: $download_link } }\n      where: { id: $id }\n    ) {\n      id\n      title\n      description\n      summary\n      image\n      download_link\n    }\n  }\n"], ["\n  mutation UpdateSketchDownloadLink($id: String!, $download_link: String!) {\n    updateSketch(\n      data: { download_link: { set: $download_link } }\n      where: { id: $id }\n    ) {\n      id\n      title\n      description\n      summary\n      image\n      download_link\n    }\n  }\n"])));
exports.UpdateSummarySketchMutation = (0, client_1.gql)(templateObject_22 || (templateObject_22 = __makeTemplateObject(["\n  mutation UpdateSketchSummary($id: String!, $summary: String!) {\n    updateSketch(data: { summary: { set: $summary } }, where: { id: $id }) {\n      id\n      title\n      description\n      summary\n      image\n      download_link\n    }\n  }\n"], ["\n  mutation UpdateSketchSummary($id: String!, $summary: String!) {\n    updateSketch(data: { summary: { set: $summary } }, where: { id: $id }) {\n      id\n      title\n      description\n      summary\n      image\n      download_link\n    }\n  }\n"])));
exports.UpdateTechCategoryMutation = (0, client_1.gql)(templateObject_23 || (templateObject_23 = __makeTemplateObject(["\n  mutation UpdateTechCategory($name: String!, $techCategoryId: String!) {\n    updateTechCategory(\n      data: { name: { set: $name } }\n      where: { id: $techCategoryId }\n    ) {\n      id\n      name\n      techs {\n        id\n        name\n      }\n    }\n  }\n"], ["\n  mutation UpdateTechCategory($name: String!, $techCategoryId: String!) {\n    updateTechCategory(\n      data: { name: { set: $name } }\n      where: { id: $techCategoryId }\n    ) {\n      id\n      name\n      techs {\n        id\n        name\n      }\n    }\n  }\n"
    // export const UpdateTechMutation = gql`
    //   mutation UpdateTech($name: String!, $techId: String!) {
    //     updateTech(data: { name: { set: $name } }, where: { id: $techId }) {
    //       id
    //       name
    //       tech_category_id
    //     }
    //   }
    // `
    // export const UpdateAboutMutation = gql``
])));
// export const UpdateTechMutation = gql`
//   mutation UpdateTech($name: String!, $techId: String!) {
//     updateTech(data: { name: { set: $name } }, where: { id: $techId }) {
//       id
//       name
//       tech_category_id
//     }
//   }
// `
// export const UpdateAboutMutation = gql``
exports.UpdateQuestionMutation = (0, client_1.gql)(templateObject_24 || (templateObject_24 = __makeTemplateObject(["\n  mutation UpdateQuestion($id: String!, $question: String!, $answer: String!) {\n    updateQuestion(\n      data: {\n        question: { set: $question }\n        answer: { update: { answer: { set: $answer } } }\n      }\n      where: { id: $id }\n    ) {\n      id\n      question\n      answer {\n        id\n        answer\n      }\n    }\n  }\n"], ["\n  mutation UpdateQuestion($id: String!, $question: String!, $answer: String!) {\n    updateQuestion(\n      data: {\n        question: { set: $question }\n        answer: { update: { answer: { set: $answer } } }\n      }\n      where: { id: $id }\n    ) {\n      id\n      question\n      answer {\n        id\n        answer\n      }\n    }\n  }\n"
    // export const UpdateAnswerMutation = gql``
    // // ##################################
    // // ############### Delete Mutations
    // // ##################################
])));
// export const UpdateAnswerMutation = gql``
// // ##################################
// // ############### Delete Mutations
// // ##################################
exports.DeleteStackMutation = (0, client_1.gql)(templateObject_25 || (templateObject_25 = __makeTemplateObject(["\n  mutation UpdateStack($id: String!, $images: String!) {\n    updateAdmin(data: { stack: { set: $images } }, where: { id: $id })\n  }\n"], ["\n  mutation UpdateStack($id: String!, $images: String!) {\n    updateAdmin(data: { stack: { set: $images } }, where: { id: $id })\n  }\n"])));
exports.DeleteProjectMutation = (0, client_1.gql)(templateObject_26 || (templateObject_26 = __makeTemplateObject(["\n  mutation DeleteProject($id: String!) {\n    deleteProject(where: { id: $id }) {\n      id\n    }\n  }\n"], ["\n  mutation DeleteProject($id: String!) {\n    deleteProject(where: { id: $id }) {\n      id\n    }\n  }\n"
    // export const DeleteMessageMutation = gql``
])));
// export const DeleteMessageMutation = gql``
exports.DeleteSketchMutation = (0, client_1.gql)(templateObject_27 || (templateObject_27 = __makeTemplateObject(["\n  mutation DeleteSketch($id: String!) {\n    deleteSketch(where: { id: $id }) {\n      id\n    }\n  }\n"], ["\n  mutation DeleteSketch($id: String!) {\n    deleteSketch(where: { id: $id }) {\n      id\n    }\n  }\n"])));
exports.DeleteTechCategoryMutation = (0, client_1.gql)(templateObject_28 || (templateObject_28 = __makeTemplateObject(["\n  mutation DeleteTechCategory($id: String!) {\n    deleteTechCategory(where: { id: $id }) {\n      id\n    }\n  }\n"], ["\n  mutation DeleteTechCategory($id: String!) {\n    deleteTechCategory(where: { id: $id }) {\n      id\n    }\n  }\n"])));
exports.DeleteTechMutation = (0, client_1.gql)(templateObject_29 || (templateObject_29 = __makeTemplateObject(["\n  mutation DeleteTech($id: String!) {\n    deleteTech(where: { id: $id }) {\n      id\n    }\n  }\n"], ["\n  mutation DeleteTech($id: String!) {\n    deleteTech(where: { id: $id }) {\n      id\n    }\n  }\n"
    // export const DeleteAboutMutation = gql``
])));
// export const DeleteAboutMutation = gql``
exports.DeleteQuestionMutation = (0, client_1.gql)(templateObject_30 || (templateObject_30 = __makeTemplateObject(["\n  mutation DeleteQuestion($id: String!) {\n    deleteQuestion(where: { id: $id }) {\n      id\n    }\n  }\n"], ["\n  mutation DeleteQuestion($id: String!) {\n    deleteQuestion(where: { id: $id }) {\n      id\n    }\n  }\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10, templateObject_11, templateObject_12, templateObject_13, templateObject_14, templateObject_15, templateObject_16, templateObject_17, templateObject_18, templateObject_19, templateObject_20, templateObject_21, templateObject_22, templateObject_23, templateObject_24, templateObject_25, templateObject_26, templateObject_27, templateObject_28, templateObject_29, templateObject_30;
