"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
exports.__esModule = true;
exports.QueryMessages = exports.QueryProjectsWithoutRelations = exports.QueryProjectsWithTechCategories = exports.QueryProjectsWithRelations = exports.QuerySingleProjectWithRelations = exports.IsThereAdminQuery = void 0;
var client_1 = require("@apollo/client");
exports.IsThereAdminQuery = (0, client_1.gql)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  query IsThereAdminQuery {\n    isThereAnAdmin\n  }\n"], ["\n  query IsThereAdminQuery {\n    isThereAnAdmin\n  }\n"])));
exports.QuerySingleProjectWithRelations = (0, client_1.gql)(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  query QuerySingleProject($id: String!) {\n    project(where: { id: $id }) {\n      id\n      name\n      app_url\n      github_url\n      image\n      type\n      summary\n      questions {\n        id\n        question\n        answer {\n          id\n          answer\n        }\n      }\n      sketches {\n        id\n        title\n        description\n        summary\n        download_link\n        image\n      }\n      tech_categories {\n        id\n        name\n        techs {\n          id\n          name\n        }\n      }\n    }\n  }\n"], ["\n  query QuerySingleProject($id: String!) {\n    project(where: { id: $id }) {\n      id\n      name\n      app_url\n      github_url\n      image\n      type\n      summary\n      questions {\n        id\n        question\n        answer {\n          id\n          answer\n        }\n      }\n      sketches {\n        id\n        title\n        description\n        summary\n        download_link\n        image\n      }\n      tech_categories {\n        id\n        name\n        techs {\n          id\n          name\n        }\n      }\n    }\n  }\n"])));
exports.QueryProjectsWithRelations = (0, client_1.gql)(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  query QueryAllProjects {\n    projects {\n      id\n      name\n      app_url\n      github_url\n      image\n      type\n      summary\n      questions {\n        id\n        question\n        answer {\n          id\n          answer\n        }\n      }\n      sketches {\n        id\n        title\n        description\n        summary\n        download_link\n        image\n      }\n      tech_categories {\n        id\n        name\n        techs {\n          id\n          name\n        }\n      }\n    }\n  }\n"], ["\n  query QueryAllProjects {\n    projects {\n      id\n      name\n      app_url\n      github_url\n      image\n      type\n      summary\n      questions {\n        id\n        question\n        answer {\n          id\n          answer\n        }\n      }\n      sketches {\n        id\n        title\n        description\n        summary\n        download_link\n        image\n      }\n      tech_categories {\n        id\n        name\n        techs {\n          id\n          name\n        }\n      }\n    }\n  }\n"])));
exports.QueryProjectsWithTechCategories = (0, client_1.gql)(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  query {\n    projects {\n      app_url\n      github_url\n      id\n      image\n      name\n      summary\n      type\n      tech_categories {\n        name\n        id\n        techs {\n          name\n          id\n        }\n      }\n    }\n  }\n"], ["\n  query {\n    projects {\n      app_url\n      github_url\n      id\n      image\n      name\n      summary\n      type\n      tech_categories {\n        name\n        id\n        techs {\n          name\n          id\n        }\n      }\n    }\n  }\n"])));
exports.QueryProjectsWithoutRelations = (0, client_1.gql)(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  query {\n    projects {\n      app_url\n      github_url\n      id\n      image\n      name\n      summary\n      type\n    }\n  }\n"], ["\n  query {\n    projects {\n      app_url\n      github_url\n      id\n      image\n      name\n      summary\n      type\n    }\n  }\n"])));
exports.QueryMessages = (0, client_1.gql)(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  query {\n    messages {\n      answer_status\n      answeredAt\n      body\n      createdAd\n      from\n      id\n      read_status\n      subject\n    }\n  }\n"], ["\n  query {\n    messages {\n      answer_status\n      answeredAt\n      body\n      createdAd\n      from\n      id\n      read_status\n      subject\n    }\n  }\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6;
